### ISSUE TITLE
Document Sqlite install on windows

### ISSUE THREAD

**Issue by kevinhughes27** [kevinhughes27/parity-server#143]
For approach-ability I think we need better documentation on how to install sqlite because the sqlite website itself wasn't adequate during the hackathon.

**Comment by wingleungchan** [comment]
Hmm... I looked into documenting this, but cannot remember how I did it. In fact, from what I remember, I just unpacked the SQLite zip files into C:\Program Files\sqlite. All the other stuff came with various Visual Studio workloads. Either it was an obvious setting that I have since forgotten or there is some magic in there.

Does anyone have a Windows VM where we can test this? I only have Windows 10 Home so cannot use HyperV. If not then I could try it on an Azure or AWS site.

**Comment by kevinhughes27** [comment]
I'm getting a new laptop shortly so I'll try it there. Hopefully putting it in `program files` works since that sounds legit. I think I put the dlls in system32 for someone at the hackathon so I know that works but I'd like to not to that in the future.

**Comment by wingleungchan** [comment]
Unless it is actually listed somewhere, I suspect that there must be some kind of implicit search path within the node.js code that will look in common locations for sqlite. This is a common behaviour with that ecosystem.

**Comment by wingleungchan** [comment]
Hmm... lots of voodoo here, but I am suspecting that we are using SQLAlchemy which uses a sqlite that is built into python itself.

**Comment by wingleungchan** [comment]
Okay, it took a bit of hunting, but I think I got it sorted out now. I am using the Python development workload in Visual Studio. That bundles in python which in turn bundles in sqlite. Then magically things work. I don't think we even needed to download sqlite separately at all. I will put together some draft notes on what I think is needed and maybe you can try it out.
